// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7oDbEHfO2jcSZBJXlFtgKtr5U9r5wP-o',
    appId: '1:1022466450338:web:f73190602eb5cb991708fb',
    messagingSenderId: '1022466450338',
    projectId: 'lexiboost-36801',
    authDomain: 'lexiboost-36801.firebaseapp.com',
    storageBucket: 'lexiboost-36801.firebasestorage.app',
    measurementId: 'G-49H138S63W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAewjBrrUSYH6ZzT8_CLWojFkOCvZxvT6o',
    appId: '1:1022466450338:android:0162743dc5bf05851708fb',
    messagingSenderId: '1022466450338',
    projectId: 'lexiboost-36801',
    storageBucket: 'lexiboost-36801.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3FYB3EMesKP-SHi1I-M1IQjpc_1NTSU8',
    appId: '1:1022466450338:ios:e2155fc9c1074e011708fb',
    messagingSenderId: '1022466450338',
    projectId: 'lexiboost-36801',
    storageBucket: 'lexiboost-36801.firebasestorage.app',
    androidClientId: '1022466450338-tjmn3herlk2thkolricfr42211d7gh0d.apps.googleusercontent.com',
    iosClientId: '1022466450338-uolccl7e030ec67oaa4qbk0i2h63i0lh.apps.googleusercontent.com',
    iosBundleId: 'com.example.lexiOnWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3FYB3EMesKP-SHi1I-M1IQjpc_1NTSU8',
    appId: '1:1022466450338:ios:e2155fc9c1074e011708fb',
    messagingSenderId: '1022466450338',
    projectId: 'lexiboost-36801',
    storageBucket: 'lexiboost-36801.firebasestorage.app',
    androidClientId: '1022466450338-tjmn3herlk2thkolricfr42211d7gh0d.apps.googleusercontent.com',
    iosClientId: '1022466450338-uolccl7e030ec67oaa4qbk0i2h63i0lh.apps.googleusercontent.com',
    iosBundleId: 'com.example.lexiOnWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7oDbEHfO2jcSZBJXlFtgKtr5U9r5wP-o',
    appId: '1:1022466450338:web:3667e1b6fe15d03a1708fb',
    messagingSenderId: '1022466450338',
    projectId: 'lexiboost-36801',
    authDomain: 'lexiboost-36801.firebaseapp.com',
    storageBucket: 'lexiboost-36801.firebasestorage.app',
    measurementId: 'G-Y1N88Q6WLD',
  );
}
