import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:lexi_on_web/admin/admin.dart';
import 'package:lexi_on_web/admin/game_dashboard.dart';
import 'package:lexi_on_web/admin/student_dashboard.dart';
import 'package:lexi_on_web/admin/teachers_dashboard.dart';
import 'package:lexi_on_web/editor/game_edit.dart';
import 'package:lexi_on_web/editor/game_manage.dart';
import 'package:lexi_on_web/editor/game_published.dart';
import 'package:lexi_on_web/editor/game_report.dart';
import 'package:lexi_on_web/editor/game_save.dart';
import 'package:lexi_on_web/editor/game_check.dart';
import 'package:lexi_on_web/editor/testing.dart';
import 'package:lexi_on_web/teacher/game_rate.dart';
import 'package:lexi_on_web/teacher/teacher_home.dart';
import 'package:lexi_on_web/teacher/teacher_profile.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

import 'package:lexi_on_web/register2.dart';
import 'package:lexi_on_web/signup folder/student.dart';
import 'package:lexi_on_web/signup folder/teacher.dart';
import 'package:lexi_on_web/start.dart';
import 'package:lexi_on_web/register.dart'; // import your register page

// Entry point
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

// Root widget
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      initialRoute: '/start', // default route
      getPages: [
        GetPage(name: '/start', page: () => const MyStart()),
        GetPage(name: '/register', page: () => const MyRegister()),
        GetPage(name: '/register2', page: () => const MyRegister2()),
        GetPage(name: '/student', page: () => const MyStudent()),
        GetPage(name: '/teacher', page: () => const MyTeacher()),
        GetPage(name: '/admin', page: () => const MyAdmin()),
        GetPage(name: '/game_edit', page: () => const MyGameEdit()),
        GetPage(name: '/game_save', page: () => const MyGameSave()),
        GetPage(name: '/teacher_home', page: () => const MyTeacherHome()),
        
        GetPage(name: '/game_published', page: () => const MyGamePublished()),
        GetPage(name: '/game_rate', page: () => const MyGameRate()),
        GetPage(name: '/game_manage', page: () => const MyManagement()),
        GetPage(name: '/game_check', page: () => const MyGameCheck()),
        GetPage(name: '/game_report', page: () => const MyGameReports()),
         GetPage(name: '/teacher_profile', page: () => const MyTeacherProfile()),
         GetPage(name: '/StudentDashboard', page: () => StudentDashboard()),
         GetPage(name: '/TeacherDashboard', page: () => const MyTeachersDashboard()),
         GetPage(name: '/game_dashboard', page: () => const MyGameDashboard()),
         GetPage(name: '/testing', page: () => const MyTesting()),
      ],
    );
  }
}
