// ===== game_create.dart =====

// ignore_for_file: library_private_types_in_public_api, use_build_context_synchronously

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:animated_button/animated_button.dart';
import 'package:get/get.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

class MyGameCreate extends StatefulWidget {
  const MyGameCreate({super.key});

  @override
  _MyGameCreateState createState() => _MyGameCreateState();
}

class _MyGameCreateState extends State<MyGameCreate> {
  int unnamedCounter = 1; // for "Unnamed (number)" games

  Future<void> _showCreateDialog() async {
    final TextEditingController titleController = TextEditingController();

    await showDialog(
      context: context,
      builder: (context) {
        return Dialog(
          backgroundColor: const Color(0xFF1E201E),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(16),
          ),
          child: SizedBox(
            width: 400,
            height: 200,
            child: Padding(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                children: [
                  Text(
                    "Create Game",
                    style: GoogleFonts.poppins(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                      color: Colors.white,
                    ),
                  ),
                  const SizedBox(height: 20),

                  // ---------------- Title Input ---------------- //
                  TextField(
                    controller: titleController,
                    style: const TextStyle( // ✅ text color
                      color: Colors.white,
                    ),
                    decoration: InputDecoration(
                      hintText: "Enter game title",
                      hintStyle: const TextStyle( // ✅ hint color
                        color: Colors.white54,
                      ),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                      contentPadding: const EdgeInsets.symmetric(
                        horizontal: 12,
                        vertical: 10,
                      ),
                    ),
                  ),


                  const Spacer(),

                  // ---------------- Buttons ---------------- //
                  Row(
                    mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                    children: [
                      AnimatedButton(
                        height: 50,
                        width: 120,
                        color: Colors.green,
                        shadowDegree: ShadowDegree.light,
                        onPressed: () async {
                          String title = titleController.text.trim();

                          if (title.isEmpty) {
                            title = "Unnamed ${unnamedCounter++}";
                          }

                          final user = FirebaseAuth.instance.currentUser;
                          if (user == null) {
                            // no logged-in user
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(
                                content: Text("You must be logged in."),
                              ),
                            );
                            return;
                          }

                          // Create document with autogenerated ID so we can safely update later
                          final docRef = FirebaseFirestore.instance
                              .collection("users")
                              .doc(user.uid)
                              .collection("created_games")
                              .doc(); // autogenerated id

                          await docRef.set({
                            "title": title,
                            "created_at": FieldValue.serverTimestamp(),
                          });

                          Navigator.pop(context); // close dialog

                          // Navigate to editor and pass the generated gameId
                          Get.toNamed("/game_edit", arguments: {"gameId": docRef.id});
                        },
                        child: Text(
                          "Create",
                          style: GoogleFonts.poppins(
                            color: Colors.white,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ),

                      AnimatedButton(
                        height: 50,
                        width: 120,
                        color: Colors.red,
                        shadowDegree: ShadowDegree.light,
                        onPressed: () {
                          Navigator.pop(context); // close dialog
                        },
                        child: Text(
                          "Close",
                          style: GoogleFonts.poppins(
                            color: Colors.white,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF1E201E),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              "Game Library",
              style: GoogleFonts.poppins(
                fontSize: 22,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 16),

            // ✅ Wrap for responsive buttons
            Expanded(
              child: SingleChildScrollView(
                child: Wrap(
                  spacing: 16,
                  runSpacing: 16,
                  alignment: WrapAlignment.start,
                  children: [
                    // ---------------- Create Button ---------------- //
                    AnimatedButton(
                      height: 250,
                      width: 250,
                      color: Colors.white,
                      shadowDegree: ShadowDegree.light,
                      onPressed: _showCreateDialog,
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          const Spacer(),
                          Image.asset(
                            "assets/others/idea.png",
                            fit: BoxFit.contain,
                            scale: 5,
                          ),
                          const Spacer(),
                          Padding(
                            padding: const EdgeInsets.all(8.0),
                            child: Text(
                              "Create",
                              style: GoogleFonts.poppins(
                                fontSize: 18,
                                fontWeight: FontWeight.bold,
                                color: Colors.black,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),

                    // ---------------- Created Levels Button ---------------- //
                    AnimatedButton(
                      height: 250,
                      width: 250,
                      color: Colors.white,
                      shadowDegree: ShadowDegree.light,
                      onPressed: () {
                        Get.toNamed("/game_save");
                      },
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          const Spacer(),
                          Image.asset(
                            "assets/others/collection.png",
                            fit: BoxFit.contain,
                            scale: 5,
                          ),
                          const Spacer(),
                          Padding(
                            padding: const EdgeInsets.all(8.0),
                            child: Text(
                              "Created Levels",
                              style: GoogleFonts.poppins(
                                fontSize: 18,
                                fontWeight: FontWeight.bold,
                                color: Colors.black,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),

                    // ---------------- Published Levels Button ---------------- //
                    AnimatedButton(
                      height: 250,
                      width: 250,
                      color: Colors.white,
                      shadowDegree: ShadowDegree.light,
                      onPressed: () {
                        debugPrint("Published Levels button clicked");
                      },
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          const Spacer(),
                          Image.asset(
                            "assets/others/game.png",
                            fit: BoxFit.contain,
                            scale: 5,
                          ),
                          const Spacer(),
                          Padding(
                            padding: const EdgeInsets.all(8.0),
                            child: Text(
                              "Published Levels",
                              style: GoogleFonts.poppins(
                                fontSize: 18,
                                fontWeight: FontWeight.bold,
                                color: Colors.black,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
